FROM andrius/asterisk

WORKDIR /etc/asterisk
RUN rm -rf ./*
COPY configs .
WORKDIR /var/lib/asterisk/sounds/
COPY sounds .
RUN apk add --update less psqlodbc asterisk-odbc asterisk-pgsql \
  &&  rm -rf /var/cache/apk/*