services:
  asterisk:
    build:
      context: .
      dockerfile: Dockerfile.ast
    restart: always
    container_name: asterisk-dev
    network_mode: "host"
    hostname: "asterisk"
    volumes:
      - ./logs:/var/log/asterisk
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.pg
    container_name: db-ns
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "jtyuajrqwzdl"
      POSTGRES_USER: admin
    volumes:
      - db-volume:/data/db
  adminer:
    image: adminer
    container_name: pg-adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  db-volume:
