services:
  asterisk:
    build:
      context: .
      dockerfile: Dockerfile.ast
    restart: always
    container_name: asterisk-dev
    hostname: "asterisk"
    volumes:
      - ./logs:/var/log/asterisk
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    ports:
      - 5060:5060/udp
      - 5061:5061/udp
      - 5160:5160/udp
      - 5161:5161/udp
      - 4569:4569/udp
      - 3478:3478/udp
  db:
    build:
      context: .
      dockerfile: Dockerfile.pg
    container_name: db-ns
    hostname: "db"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "jtyuajrqwzdl"
      POSTGRES_USER: admin
    volumes:
      - db-volume:/data/db
    healthcheck:
      test: pg_isready -U admin -d asterisk
      interval: 10s
      timeout: 3s
      retries: 3
  adminer:
    image: adminer
    container_name: pg-adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
volumes:
  db-volume:
